### PR TITLE
Support Jupiter Lab

### LINKED ISSUE #25: Support of Jupyter Lab
Hi,

The kernel doesn't seems to work with Jupyter Lab (0.34.12): I mean sometimes I have response for `printlnl!("...");` but often no response.

I started to investigate (I open the ticket to inform about the issue, and my progress).

After reading https://github.com/jupyterlab/jupyterlab/issues/470 I noticed some similarities. I try to add status: idle after every shell request, and that seems to fix the issue about println! and lot of kernel_info_request. But not with the support of evcxr_display. I plan to check the protocol 5.x implementation and to make PR asap.

PS: It's my first day with Jupyter Lab and the kernel / client api.

### PR DESCRIPTION
**Pull request by davidB**
Without the fix, Jupyter Lab loops on "kernel_info_request", and the kernel never process cell's code.
see https://github.com/jupyterlab/jupyterlab/issues/470

- I'm able to see result of cell with `println!("hello");` in Jupyter notebook, Jupyter Lab & nteract. 
- display of result of evcxr_display is now visible in Jupyter Lab, notebook & nteract
- display of json content can be displayed by JupyterLab default renderer (vega-lite, json)

Jupiter Lab display

fix #25

### CODE REVIEW

**Comment by davidB** [comment]
The PR failed like the master : 
```
error: Could not compile `zmq`.
```

**Comment by davidlattimore** [comment]
Thanks for the fixes and sorry about the failing CI. I'm still setting it up

**Comment by davidB** [comment]
np, I also tried to take a look at travis' issue or alternatives as travis used a too old version of ubuntu.
When you'll publish a new version, we could retry the binder PR.

**Comment by davidlattimore** [comment]
Build is passing now :)

Publishing a new version might help with the binder PR?

**Comment by davidB** [comment]
Yes, see my comments on PR #

**Pull request merged**
